### ISSUE TITLE
How to apply the XML files as background?

### ISSUE THREAD

**Issue by puspamadak** [Vergil333/dynamic-mac-like-wallpaper-and-lockscreen#1]
I did all according to the instructions on the main page, but my background shows a black colour. What did you mean by the last line? Probably that is causing the problem because I cannot fully understand what it meant.
> go to gnome tweaks -> Appearance -> Background/Lock Screen -> Image and put the xml files in there

**Comment by Vergil333** [comment]
Hi! Do you use Ubuntu? You need to install gnome tweaks. Here's [how to](https://linuxconfig.org/how-to-install-tweak-tool-on-ubuntu-20-04-lts-focal-fossa-linux).

Then lunch gnome tweaks and proceed by the last line.

**Comment by puspamadak** [comment]
Thanks for the response. It worked.
